server:
  port: 8080
  servlet:
    context-path: /
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myown?characterEncoding=utf8
#    username: root
#    password: root
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 30000
#      validation-query: select 'x'
#      test-while-idle: true
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: le.ac.uk.entity
#  configuration:
#    cache-enabled: true


